version: '3.8'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./src/PlgSystemNoExtLinks.php
        target: /var/www/html/plugins/system/noextlinks/noextlinks.php
        consistency: delegated
      - type: bind
        source: ./src/noextlinks.xml
        target: /var/www/html/plugins/system/noextlinks/noextlinks.xml
        consistency: delegated
      - type: bind
        source: ./src/noextlinks.js
        target: /var/www/html/plugins/system/noextlinks/noextlinks.js
        consistency: delegated
      - type: bind
        source: ./src/Support
        target: /var/www/html/plugins/system/noextlinks/Support
        consistency: delegated
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example